---
driver:
  name: vagrant
  customize:
    memory: 1024

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
    run_list:
      - recipe[apt::default]

suites:
  - name: default
    run_list:
      - recipe[docker_host::default]
